// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz6Kr7qtAi5R6vR4m8BVP8wt-M0m8D6d8',
    appId: '1:771704064747:web:d124f6089929b7e0ac4cae',
    messagingSenderId: '771704064747',
    projectId: 'ecommerce-store-5546c',
    authDomain: 'ecommerce-store-5546c.firebaseapp.com',
    storageBucket: 'ecommerce-store-5546c.firebasestorage.app',
    measurementId: 'G-LCEPB1RMKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByvAEZzvBqpxE8MKiwvTeZhufy9L8h-M4',
    appId: '1:771704064747:android:00a626b9cdbc60c5ac4cae',
    messagingSenderId: '771704064747',
    projectId: 'ecommerce-store-5546c',
    storageBucket: 'ecommerce-store-5546c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmq-2rVLVa9uM38e2bHmJkIfhg25-rLX4',
    appId: '1:771704064747:ios:63531280d5c5b193ac4cae',
    messagingSenderId: '771704064747',
    projectId: 'ecommerce-store-5546c',
    storageBucket: 'ecommerce-store-5546c.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmq-2rVLVa9uM38e2bHmJkIfhg25-rLX4',
    appId: '1:771704064747:ios:63531280d5c5b193ac4cae',
    messagingSenderId: '771704064747',
    projectId: 'ecommerce-store-5546c',
    storageBucket: 'ecommerce-store-5546c.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz6Kr7qtAi5R6vR4m8BVP8wt-M0m8D6d8',
    appId: '1:771704064747:web:efa4ba696239f941ac4cae',
    messagingSenderId: '771704064747',
    projectId: 'ecommerce-store-5546c',
    authDomain: 'ecommerce-store-5546c.firebaseapp.com',
    storageBucket: 'ecommerce-store-5546c.firebasestorage.app',
    measurementId: 'G-G2WCD3Q7KL',
  );
}
